services:
  - type: web
    name: car-rental-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://database_d8xt_user:UO3B9Txna4ff1rRV8U8kirynnbq0pLuB@dpg-d66lf975r7bs739a7j10-a/database_d8xt
      - key: SPRING_PROFILES_ACTIVE
        value: render
