databases:
  - name: car-rental-db
    plan: free
    databaseName: carrentalapplication
    user: carrentaluser

services:
  - type: web
    name: car-rental-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-rental-db
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: render
